channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bcftools=1.10.2
  - bedtools=2.29.2
  - biopython=1.76
  - click=7.1.2
  - curl=7.68.0
  - matplotlib=3.2.1
  - numba=0.48.0
  - numpy=1.17.0
  - pip=19.3.1
  - progressbar=2.5
  - pysam=0.15.3
  - python=3.6.7
  - r-adaptivetau=2.2_3
  - r-base=3.6.1
  - r-coda=0.19_2
  - r-daag=1.22.1
  - r-data.table=1.12.2
  - r-desolve=1.28
  - r-dplyr=0.8.5
  - r-expm=0.999_4
  - r-ggplot2=3.1.1
  - r-ggridges=0.5.1
  - r-jsonlite=1.6
  - r-purrr=0.3.2
  - r-r.utils=2.8.0
  - r-reader=1.0.6
  - r-rjson=0.2.20
  - r-scales=1.0.0
  - r-stringr=1.4.0
  - r-viridis=0.5.1
  - scipy=1.4.1
  - snakemake=5.12.3
  - tqdm=4.46.0
  - bioconductor-txdb.athaliana.biomart.plantsmart25
  - r-reshape2=1.4.4
  - r-tidyverse=1.3.0
  - r-optparse=1.6.2